# -*- coding: utf-8 -*-
"""MovieDataset_DownloadAndPreprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HNp--6EzG64dMfxgGRqDqnJdIRtbtC1A
"""

import pandas as pd
import numpy as np

# ==============================
# IMDb dataset URLs
# ==============================
BASICS_URL = "https://datasets.imdbws.com/title.basics.tsv.gz"
RATINGS_URL = "https://datasets.imdbws.com/title.ratings.tsv.gz"

print("Downloading IMDb datasets...")

# ==============================
# Load datasets
# ==============================
basics = pd.read_csv(
    BASICS_URL,
    sep="\t",
    compression="gzip",
    na_values="\\N",
    low_memory=False
)

ratings = pd.read_csv(
    RATINGS_URL,
    sep="\t",
    compression="gzip",
    na_values="\\N"
)

print("Processing movie data...")

# ==============================
# Filter movies only
# ==============================
movies = basics[
    (basics["titleType"] == "movie") &
    (basics["isAdult"] == 0)
][["tconst", "primaryTitle", "startYear", "genres"]]

# Merge ratings
movies = movies.merge(ratings, on="tconst", how="left")

# Clean columns
movies["startYear"] = pd.to_numeric(movies["startYear"], errors="coerce")
movies = movies.dropna(subset=["averageRating", "startYear"])

movies["startYear"] = movies["startYear"].astype(int)

movies.rename(columns={
    "primaryTitle": "title",
    "averageRating": "rating",
    "numVotes": "votes",
    "startYear": "year"
}, inplace=True)

# Fill missing
movies["title"] = movies["title"].fillna("")
movies["genres"] = movies["genres"].fillna("")

# Remove duplicates
movies["clean_title"] = movies["title"].str.lower().str.strip()
movies = movies.drop_duplicates(subset="clean_title")

# ==============================
# Save CSV
# ==============================
movies.to_csv("movies_small.csv", index=False)

print("SUCCESS ✅")
print("File saved as: movies_small.csv")
print("Total movies:", len(movies))