# -*- coding: utf-8 -*-
"""RatingsDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqmghFZcJzie7NW4EtIOHCrmYu8XmHxl
"""

import os
import zipfile
import urllib.request
import pandas as pd

# MovieLens 100K dataset URL
DATA_URL = "https://files.grouplens.org/datasets/movielens/ml-100k.zip"
ZIP_NAME = "ml-100k.zip"
EXTRACT_DIR = "ml-100k"

# Step 1: Download dataset
if not os.path.exists(ZIP_NAME):
    print("Downloading MovieLens 100K dataset...")
    urllib.request.urlretrieve(DATA_URL, ZIP_NAME)

# Step 2: Extract zip
if not os.path.exists(EXTRACT_DIR):
    print("Extracting dataset...")
    with zipfile.ZipFile(ZIP_NAME, "r") as zip_ref:
        zip_ref.extractall()

# Step 3: Convert u.data to ratings.csv
print("Creating ratings.csv...")

ratings = pd.read_csv(
    os.path.join(EXTRACT_DIR, "u.data"),
    sep="\t",
    names=["userId", "movieId", "rating", "timestamp"]
)

ratings.to_csv("ratings.csv", index=False)

print("SUCCESS ✅")
print("ratings.csv created in project directory")